# Generated by Django 6.0 on 2026-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='assessment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='assessment_data',
            field=models.JSONField(blank=True, default=list, help_text='List of past assessment snapshots [{date, scores, analysis_summary}]'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, help_text='List of chat messages [{id, role, text, timestamp}]'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_assessment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
