# Generated by Django 6.0 on 2026-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_visitor_assessment_count_visitor_assessment_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('dismissed', 'Dismissed'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='new', max_length=16),
        ),
    ]
