# Generated by Django 5.2.8 on 2026-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='current_answers',
            field=models.JSONField(blank=True, default=dict, help_text='In-progress assessment answers {subAssessmentId: {questionId: answerValue}}'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Last active step (0=form, 1=system select, 3=assessment)'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='current_system_id',
            field=models.CharField(blank=True, default='', help_text='ID of the system currently being assessed', max_length=64),
        ),
    ]
