import React, { useMemo } from "react";
import { CANONICAL_SYSTEMS } from "../../constants/systems";
import {
  FaBrain, FaCheckCircle, FaExclamationTriangle, FaLightbulb,
  FaTimes, FaRobot, FaDownload, FaSpinner,
} from "react-icons/fa";


export default function AINarration({ onClose, darkMode, summary, loading, error }) {
  /* ── Derived analysis from real data ── */
  const analysis = useMemo(() => {
    if (!summary) return null;

    const systems    = summary.systems || [];
    const orgHealth  = summary.org_health;
    const confidence = summary.confidence;
    const recs       = summary.top_recommendations || [];
    const forecast   = summary.health_forecast;
    const cultural   = summary.organizational_insights || {};
    const transform  = summary.transformation_readiness;
    const deps       = summary.cross_system_dependencies || [];

    const strong = systems.filter((s) => (s.score ?? 0) >= 70);
    const weak   = systems.filter((s) => (s.score ?? 0) < 50 && s.score != null);

    /* Executive summary */
    const execParts = [];
    if (orgHealth != null) {
      execParts.push(`Overall organizational health is ${orgHealth}%${confidence != null ? ` (confidence ${confidence}%)` : ""}.`);
    }
    if (strong.length) {
      const labels = strong.map((s) => CANONICAL_SYSTEMS.find((c) => c.key === s.key)?.title || s.key);
      execParts.push(`Key strengths: ${labels.join(", ")}.`);
    }
    if (weak.length) {
      const labels = weak.map((s) => CANONICAL_SYSTEMS.find((c) => c.key === s.key)?.title || s.key);
      execParts.push(`Critical attention needed: ${labels.join(", ")}.`);
    }
    if (forecast?.projected_health != null) {
      execParts.push(`30-day projected health: ${forecast.projected_health}% (${forecast.trend || "stable"}).`);
    }
    const executiveSummary = execParts.length ? execParts.join(" ") : "No assessment data available.";

    /* Critical insights */
    const criticalInsights = [];
    weak.forEach((s) => {
      criticalInsights.push(`${CANONICAL_SYSTEMS.find((c) => c.key === s.key)?.title || s.key}: Score of ${s.score}% requires immediate intervention`);
    });
    systems.forEach((s) => {
      (s.risk_factors || []).forEach((rf) => {
        criticalInsights.push(`${CANONICAL_SYSTEMS.find((c) => c.key === s.key)?.title || s.key} risk: ${rf.impact}`);
      });
    });
    if (forecast?.risk_areas?.length) {
      forecast.risk_areas.forEach((r) => {
        criticalInsights.push(`${r.system} — ${r.risk_level} risk, mitigate in ${r.mitigation_timeline}`);
      });
    }

    /* Recommendations */
    const recommendations = recs.map((r) => `${r.action}${r.expected_impact ? ` (${r.expected_impact})` : ""}`);

    /* Next steps */
    const nextSteps = [];
    if (weak.length) nextSteps.push("Prioritize quick-win interventions for underperforming systems");
    if (deps.length) nextSteps.push(`Address ${deps.length} cross-system dependencies`);
    if (transform?.overall != null) nextSteps.push(`Transformation readiness at ${transform.overall}% — build change-management capacity`);
    nextSteps.push("Schedule follow-up assessment in 30 days");
    nextSteps.push("Monitor forecast trends on the Benchmarking & Trends page");

    /* Cultural snapshot */
    const cultureEntries = Object.entries(cultural);

    return { executiveSummary, criticalInsights, recommendations, nextSteps, cultureEntries, orgHealth, systems };
  }, [summary]);

  /* ── Export ── */
  const exportReport = () => {
    if (!analysis) return;
    const txt = `CONSEQ-X ORGANIZATIONAL ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}
${"=".repeat(50)}

EXECUTIVE SUMMARY
${analysis.executiveSummary}

CRITICAL INSIGHTS
${analysis.criticalInsights.map((i) => `  • ${i}`).join("\n") || "  None"}

STRATEGIC RECOMMENDATIONS
${analysis.recommendations.map((r) => `  • ${r}`).join("\n") || "  None"}

NEXT STEPS
${analysis.nextSteps.map((s) => `  • ${s}`).join("\n")}

SYSTEM SCORES
${analysis.systems.map((s) => `  ${CANONICAL_SYSTEMS.find((c) => c.key === s.key)?.title || s.key}: ${s.score ?? "—"}%`).join("\n")}

${analysis.cultureEntries.length ? `ORGANIZATIONAL CULTURE\n${analysis.cultureEntries.map(([k, v]) => `  ${k.replace(/_/g, " ")}: ${v}%`).join("\n")}` : ""}
${"=".repeat(50)}
Generated by ConseQ-X Analysis Engine
`;
    const blob = new Blob([txt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = `ConseQ-X-Analysis-${new Date().toISOString().split("T")[0]}.txt`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
  };

  /* ── Render ── */
  const card = (border, bg) => `p-4 rounded-lg border ${darkMode ? `${bg} ${border}` : `${bg} ${border}`}`;

  return (
    <div className="max-h-[80vh] overflow-y-auto p-6" style={{ scrollbarWidth: "none" }}>
      {/* Header */}
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-gradient-to-r from-emerald-500 to-blue-500">
            <FaRobot className="text-white" size={20} />
          </div>
          <div>
            <h2 className="text-lg font-semibold">Organizational Analysis</h2>
            <p className={`text-sm ${darkMode ? "text-gray-400" : "text-gray-500"}`}>Data-driven executive summary from your assessments</p>
          </div>
        </div>
        <button onClick={onClose} className={`p-2 rounded-lg ${darkMode ? "hover:bg-gray-800 text-gray-400" : "hover:bg-gray-100 text-gray-600"}`}>
          <FaTimes size={16} />
        </button>
      </div>

      {/* Loading */}
      {loading && (
        <div className="flex items-center justify-center py-12 text-gray-400 gap-2">
          <FaSpinner className="animate-spin" /> Preparing analysis…
        </div>
      )}

      {/* Error */}
      {error && !loading && (
        <div className={card("border-red-700", darkMode ? "bg-red-900/20" : "bg-red-50")}>
          <FaExclamationTriangle className="text-red-500 inline mr-2" />
          <span className="text-sm">{error}</span>
        </div>
      )}

      {/* Analysis body */}
      {analysis && !loading && (
        <div className="space-y-5">
          {/* Executive Summary */}
          <div className={card(darkMode ? "border-blue-800" : "border-blue-200", darkMode ? "bg-blue-900/20" : "bg-blue-50")}>
            <div className="flex items-center gap-2 mb-2"><FaCheckCircle className="text-blue-500" /><h3 className="font-medium">Executive Summary</h3></div>
            <p className="text-sm leading-relaxed">{analysis.executiveSummary}</p>
          </div>

          {/* Critical Insights */}
          {analysis.criticalInsights.length > 0 && (
            <div className={card(darkMode ? "border-yellow-800" : "border-yellow-200", darkMode ? "bg-yellow-900/20" : "bg-yellow-50")}>
              <div className="flex items-center gap-2 mb-2"><FaExclamationTriangle className="text-yellow-500" /><h3 className="font-medium">Critical Insights</h3></div>
              <ul className="space-y-1">{analysis.criticalInsights.map((t, i) => <li key={i} className="text-sm flex gap-2"><span className="text-yellow-500">•</span>{t}</li>)}</ul>
            </div>
          )}

          {/* Recommendations */}
          {analysis.recommendations.length > 0 && (
            <div className={card(darkMode ? "border-green-800" : "border-green-200", darkMode ? "bg-green-900/20" : "bg-green-50")}>
              <div className="flex items-center gap-2 mb-2"><FaLightbulb className="text-green-500" /><h3 className="font-medium">Strategic Recommendations</h3></div>
              <ul className="space-y-1">{analysis.recommendations.map((t, i) => <li key={i} className="text-sm flex gap-2"><span className="text-green-500">•</span>{t}</li>)}</ul>
            </div>
          )}

          {/* Next Steps */}
          <div className={card(darkMode ? "border-purple-800" : "border-purple-200", darkMode ? "bg-purple-900/20" : "bg-purple-50")}>
            <div className="flex items-center gap-2 mb-2"><FaBrain className="text-purple-500" /><h3 className="font-medium">Next Steps</h3></div>
            <ul className="space-y-1">{analysis.nextSteps.map((t, i) => <li key={i} className="text-sm flex gap-2"><span className="text-purple-500">•</span>{t}</li>)}</ul>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
            <button onClick={exportReport} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 flex items-center gap-2">
              <FaDownload size={14} /> Export Report
            </button>
            <button onClick={onClose} className={`px-4 py-2 rounded-lg text-sm border ${darkMode ? "border-gray-600 hover:bg-gray-800" : "border-gray-300 hover:bg-gray-50"}`}>
              Close
            </button>
          </div>
        </div>
      )}

      {/* No data */}
      {!analysis && !loading && !error && (
        <div className={`rounded-xl p-8 text-center text-sm ${darkMode ? "bg-gray-800 text-gray-400" : "bg-gray-50 text-gray-500"}`}>
          No assessment data available — run assessments first
        </div>
      )}
    </div>
  );
}
